print("Erhalte Informationen von +49 174 8830551...")
print("")
print("Betreiber : VODAFONE")
print("Standort : Storkow (Mark), Brandenburg")
print("Akkumulator in % : 67")
print("Handynummer registriert auf : Milano El Egit")
print("Empfang : 2/4")
print("Letzte geöffnete Applikation : Ameza")
